[docker]
#dockerconfigjson="/Users/qnguyen/work/S3Blitzer/.secrets/dockercred"
dockerconfigjson=""

[service]
locust_image="index.docker.io/quannguyen2281995/s3blitzer:linux_amd64_latest"
locust_workers=4

[aws]
target_region="eu-central-1"
cluster_name="k8s-loadtests"

[eks]
ami_type="AL2_x86_64"

    [eks.node_group]
        [eks.node_group.one]
        name="node-group-1"
        instance_types=["t3.small"]
        min_size=1
        max_size=2
        desired_size=2