apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-worker
  labels:
    app: locust-worker
spec:
  replicas: 4
  selector:
    matchLabels:
      app: locust-worker
  template:
    metadata:
      labels:
        app: locust-worker
    spec:
      containers:
      - name: locust-worker
        image: s3blitzer:latest
        imagePullPolicy: Never
        command: [ "locust" ]
        args: [ "-f", "/s3blitzer/s3blitzer.py", "--worker", "--master-host", "locust-master-private" ]

